export enum Genres {
  ROCK = "rock",
  POP = "pop",
  JAZZ = "jazz",
  CLASSICAL = "classical",
  ELECTRONIC = "electronic",
  HIP_HOP = "hip_hop",
  R_AND_B = "r_and_b",
  COUNTRY = "country",
  FOLK = "folk",
  METAL = "metal",
  BLUES = "blues",
  REGGAE = "reggae",
  PUNK = "punk",
  INDIE = "indie",
  ALTERNATIVE = "alternative",
  LATIN = "latin",
  WORLD = "world",
  EXPERIMENTAL = "experimental",
}
